=== HugoRibeiro38/PEI_8200441_8200278_8200489/Basex/webapp/XSD_XML/reservations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.NCar.com/"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.NCar.com/"
           xmlns:c="http://www.NCar.com/commonTypes.xsd"
           elementFormDefault="qualified">

<xs:import schemaLocation="commonTypes.xsd" namespace="http://www.NCar.com/commonTypes.xsd"></xs:import>


<xs:element name="reservations">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="partnerName" type="c:identificationType" minOccurs="1" maxOccurs="1" />
            <xs:element name="expertiseName" type="c:identificationType" minOccurs="1" maxOccurs="1" />
            <xs:element name="date" type="c:ISODateTime" minOccurs="1" maxOccurs="1"/><!-- Atributo adicional -->
            <xs:element name="reservation" type="reservationType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- ComplexType Reservation -->
<xs:complexType name="reservationType">
        <xs:sequence>
            <xs:element name="code" type="c:codeType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Start" type="c:ISODateTime" minOccurs="1" maxOccurs="1" /> <!-- Atributo adicional do dia, a hora e min são obrigatorios -->
            <xs:element name="End" type="c:ISODateTime" minOccurs="1" maxOccurs="1" /> <!-- Atributo adicional do dia, a hora e min são obrigatorios -->
            <xs:element name="address" type="addressType" minOccurs="1" maxOccurs="1"/>
            <xs:element name = "vehicleInfo" type="infoVehicleType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="typeOfContact" type="contactOf" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    
    
                   <!-- Tipo complexo para Tipo de contacto -->
    <!-- ao instanciarmos em XML usamos ou elemento Cliente para dizer que 
    o contacto é com o cliente dando respetiva Info e RepairShop para o caso de ser uma Oficina-->
    
    
    <xs:complexType name="contactOf">
        <xs:choice>
            <xs:element name="client" type="clientType"/>
            <xs:element name="RepairShop" type="repairShopType"/>
        </xs:choice>
    </xs:complexType>
    
    <!-- No caso de o contacto ser com o cliente é fornecida a respetiva Informação -->
    <xs:complexType name="clientType">
        <xs:all>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="property" type="propertyType" minOccurs="1" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    
    <!-- ComplextType para o caso de o contacto ser com a Oficina -->
    <xs:complexType name="repairShopType">
        <xs:all>
            <xs:element name="establishmentName" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    
    <!-- SimpleType para restringir se o cliente é dono ou não do carro -->
    <xs:simpleType name="propertyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Owner"/>
            <xs:enumeration value="Not Owner"/>
        </xs:restriction>
    </xs:simpleType>
    

<!-- ComplexType for Address -->
  <xs:complexType name="addressType">
    <xs:sequence>
        <xs:element name = "street" type="c:streetAddressType" minOccurs="1" maxOccurs="1"/>
        <xs:element name = "numDoor" type="c:numDoorType" minOccurs="1" maxOccurs="1"/>
        <xs:element name = "zipCode" type="c:zipCodeType" minOccurs="1" maxOccurs="1"/>
        <xs:element name = "city" type="c:cityType" minOccurs="1" maxOccurs="1"/>
        <xs:element name = "coordinates" type="coordinatesType" minOccurs="0"/>
    </xs:sequence>
</xs:complexType>

<!-- ComplexType for Coordinates -->
<xs:complexType name="coordinatesType">
        <xs:sequence>
            <xs:element name = "latitude" type="c:latitudeType" minOccurs="0"/>
            <xs:element name = "longitude" type="c:longitudeType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <!-- ComplexType for VehicleInfo -->
    
    <xs:complexType name="infoVehicleType">
        <xs:sequence>
            <xs:element name="brand" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name ="model" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="fuel" type="c:fuelType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="transmission" type="c:gearsType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="year" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
            <xs:element name = "horsePower" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
   
</xs:schema>

=== HugoRibeiro38/PEI_8200441_8200278_8200489/Basex/webapp/XSD_XML/reservations.xml
<?xml version="1.0" encoding="UTF-8"?>
<reservations xmlns="http://www.NCar.com/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.NCar.com/ reservations.xsd"
    xmlns:c="http://www.NCar.com/commonTypes.xsd">


    <partnerName>A2A3</partnerName>
    <expertiseName>A4S5</expertiseName>
    <date>2022-12-08T12:00:00Z</date>


    <!-- Reserva COD 12 -->
    <reservation>

        <code>12</code>
        <Start>2022-12-08T08:00:00Z</Start>
        <End>2022-12-08T12:00:00Z</End>
        <address>
            <street>Rua do Curral</street>
            <numDoor>12</numDoor>
            <zipCode>4610-156</zipCode>
            <city>Felgueiras</city>
            <coordinates></coordinates> <!-- caso não seja possível fornecer coordenadas basta apenas
            não chamar elemento coordinates ou chamar e não chamar latitude e longitude-->
        </address>

        <vehicleInfo>
            <brand>Ford</brand>
            <model>Fiesta</model>
            <fuel>Diesel</fuel>
            <transmission>Manual</transmission>
            <year>1998</year>
            <horsePower>76</horsePower>
        </vehicleInfo>
        <typeOfContact>
            <client>
                <name>José Meireles</name>
                <property>Owner</property>
            </client>
        </typeOfContact>
    </reservation>

    <reservation>
        <code>14</code>
        <Start>2022-12-08T07:00:00Z</Start>
        <End>2022-12-08T11:00:00Z</End>
        <address>
            <street>Rua do Curral</street>
            <numDoor>12</numDoor>
            <zipCode>4615-172</zipCode>
            <city>Lixa</city>
            <coordinates>
                <latitude>23.4</latitude> <!-- Caso seja possível enviar coordenadas : xs:decimal -->
                <longitude>35</longitude> <!-- Caso seja possível enviar coordenadas xs:integer -->
            </coordinates>
        </address>

        <vehicleInfo>
            <brand>Opel</brand>
            <model>Corsa</model>
            <fuel>Gasoline</fuel>
            <transmission>Manual</transmission>
            <year>2008</year>
            <horsePower>80</horsePower>
        </vehicleInfo>
        <typeOfContact>
            <client>
                <name>Ana Ribeiro</name>
                <property>Not Owner</property>
            </client>
        </typeOfContact>
    </reservation>


</reservations>
